name: Run Badminton

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * *'
  workflow_dispatch: 
  push:
    branches: "**"
  pull_request:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Docker Layers Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Set Variables
        id: vars
        run: |
          if [ "$GITHUB_REF_NAME" != "master" ]; then
            echo "::set-output name=norun::yes"
          fi
      - name: Run the badminton organizer by building the Docker image
        env:
          ICAL_TMPL: ${{ secrets.ICAL_TMPL }}
          WEB_CREDS: ${{ secrets.WEB_CREDS }}
          GCAL_CLI_CACHE: ${{ secrets.GCAL_CLI_CACHE }}
          GCAL_CLI_OAUTH: ${{ secrets.GCAL_CLI_OAUTH }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DEBUG: ${{ secrets.DEBUG }}
          CLUB_MANAGER_TELEGRAM_NICK: ${{ secrets.CLUB_MANAGER_TELEGRAM_NICK }}

        run: docker build . --file Dockerfile --tag bad:$(date +%s) --build-arg NO_RUN="${{steps.vars.outputs.norun}}" --build-arg DEBUG="${DEBUG}" --build-arg ICAL_TMPL="${ICAL_TMPL}" --build-arg WEB_CREDS="${WEB_CREDS}" --build-arg GCAL_CLI_CACHE="${GCAL_CLI_CACHE}" --build-arg GCAL_CLI_OAUTH="${GCAL_CLI_OAUTH}" --build-arg TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}" --build-arg TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID}"  --build-arg CLUB_MANAGER_TELEGRAM_NICK="${CLUB_MANAGER_TELEGRAM_NICK}" 

