name: Run Badminton

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * *'
  workflow_dispatch: 
  push:
    branches: "**"
  pull_request:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set Variables
        id: vars
        run: |
          if [ "$GITHUB_REF_NAME" != "master" ]; then
            echo "::set-output name=nospam::no-please"
          fi
      - name: Run the badminton organizer by building the Docker image
        uses: docker/build-push-action@v3
        env:
          ICAL_TMPL: ${{ secrets.ICAL_TMPL }}
          WEB_CREDS: ${{ secrets.WEB_CREDS }}
          GCAL_CLI_CACHE: ${{ secrets.GCAL_CLI_CACHE }}
          GCAL_CLI_OAUTH: ${{ secrets.GCAL_CLI_OAUTH }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DEBUG: ${{ secrets.DEBUG }}
          CLUB_MANAGER_TELEGRAM_NICK: ${{ secrets.CLUB_MANAGER_TELEGRAM_NICK }}
        with:
          context: .
          tags: bad:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NO_SPAM=${{ steps.vars.outputs.nospam }}
            DEBUG=${{ secrets.DEBUG }}
            ICAL_TMPL=${{ secrets.ICAL_TMPL }}
            WEB_CREDS=${{ secrets.WEB_CREDS }}
            GCAL_CLI_OAUTH=${{ secrets.GCAL_CLI_OAUTH }}
            GCAL_CLI_CACHE=${{ secrets.GCAL_CLI_CACHE }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
            CLUB_MANAGER_TELEGRAM_NICK=${{ secrets.CLUB_MANAGER_TELEGRAM_NICK }}



















