name: Run Badminton

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * *'
  workflow_dispatch: 
  push:
    branches: "**"
  pull_request:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Configuration
        id: config
        run: |
          if [ "$GITHUB_REF_NAME" != "master" ]; then
            echo "::set-output name=nospam::no-please"
          fi
          
          echo "::set-output name=build_version::$GITHUB_RUN_ID"
          
          mkdir -p ./config/auth && mkdir -p ./config/gcalcli
          
          echo "${{ secrets.ICAL_TMPL }}" > ./config/ical.tmpl
          echo "${{ secrets.WEB_CREDS }}" > ./config/auth/web-creds
          echo "${{ secrets.GCALCLI_OAUTH_ENCODED }}" > ./config/gcalcli/oauth
          echo "${{ secrets.GCALCLI_CACHE_ENCODED }}" > ./config/gcalcli/cache

      - name: Run the badminton organizer by building the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: bad:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secret-files: |
            ical=./config/ical.tmpl
            web-creds=./config/auth/web-creds
            gcalcli-oauth=./config/gcalcli/oauth
            gcalcli-cache=./config/gcalcli/cache
          build-args: |
            NO_SPAM=${{ steps.config.outputs.nospam }}
            DEBUG=${{ secrets.DEBUG }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
            CLUB_MANAGER_TELEGRAM_NICK=${{ secrets.CLUB_MANAGER_TELEGRAM_NICK }}
            BUILD_VERSION=${{ steps.config.outputs.build_version }}



















